/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lam.cenicco.util;

/**
 *
 * @author Antonio Durán
 */
public enum EtiquetasSat {

    PERCEPCION("<nomina12:Percepcion TipoPercepcion=\"#NODO\" Clave=\"#NUMCONC\" Concepto=\"#NOMCONC\" ImporteGravado=\"#IMPORTGRAV\" ImporteExento=\"#IMPORTEEXT\">"),
    CIERRE_PERCEPCIONES("</nomina12:Percepcion>"),
    DEDUCCION("<nomina12:Deduccion TipoDeduccion=\"#NODO\" Clave=\"#NUMCONC\" Concepto=\"#NOMCONC\" Importe=\"#IMPORTEEXT\"/>"),
    HORAS_EXTRAS("<nomina12:HorasExtra Dias=\"1\" TipoHoras=\"#TIPOHORAS\" HorasExtra=\"#TIEMPOHORAS\" ImportePagado=\"#IMPORTEHORAS\"/>"),
    INCAPACIDAD("<nomina12:Incapacidad DiasIncapacidad=\"#DIASINCAPACIDAD\" TipoIncapacidad=\"#TIPOINCAPACIDAD\" ImporteMonetario=\"#IMPORTEINCAPACIDAD\"/>"),
    OTROS_PAGOS("<nomina12:OtroPago TipoOtroPago=\"#NODO\" Clave=\"#NUMCONC\" Concepto=\"#NOMCONC\" Importe=\"#IMPORTEEXT\\\">"
    + "<nomina12:SubsidioAlEmpleo SubsidioCausado=\"#SUBSIDIOCAUSADO\"/>"
    + "</nomina12:OtroPago>"),
    CIERRE_INCAPACIDADES("</nomina12:Incapacidades>"),
    ABRIR_INCAPACIDADES("<nomina12:Incapacidades>"),
    ABRIR_OTROSPAGOS("<nomina12:OtrosPagos>"),
    CIERRE_OTROSPAGOS("</nomina12:OtrosPagos>"),
    //    
    ENCABEZADO_IMPUESTO_RETENIDO("TotalImpuestosRetenidos=\"#IMPUESTORETENIDO\""),
    //    
    SUBCONTRATACION("<nomina12:SubContratacion RfcLabora=\"#RFCSUBCONTRATACION\" PorcentajeTiempo=\"100\"></nomina12:SubContratacion>"),
    BUSCAR_ATRIBUTO_CURP_EMISOR("#ATRIBUTO_CURP_EMISOR"),
    ATRIBUTO_CURP_EMISOR("Curp=\"#CURP_EMISOR\""),
    BUSCAR_CURP_EMISOR("#CURP_EMISOR"),
    NODO_SUBCONTRATACION("#NODOSUBCONTRATACION"),
    NODO("#NODO"),
    NUMERO_CONCEPTO("#NUMCONC"),
    NOMBRE_CONCEPTO("#NOMCONC"),
    IMPORTE_GRAVADO("#IMPORTGRAV"),
    IMPORTE_EXENTO("#IMPORTEEXT"),
    TIPO_HORAS("#TIPOHORAS"),
    TIEMPO_HORAS("#TIEMPOHORAS"),
    IMPORTE_HORAS("#IMPORTEHORAS"),
    DIAS_INCAPACIDAD("#DIASINCAPACIDAD"),
    TIPO_INCAPACIDAD("#TIPOINCAPACIDAD"),
    IMPORTE_INCAPACIDAD("#IMPORTEINCAPACIDAD"),
    INDEMNIZACION("#INDEMNIZACION"),
    //    
    NOMINA_ESPECIAL("#NOMINAESPECIAL"),
    CERTIFICADO("#CERTIFICADO"),
    NUMEROCERTIFICADO("#NUMEROCERTIFICADO"),
    SERIE("#SERIE"),
    FOLIO("#FOLIO"),
    FECHA_ACTUAL("#FECHAACTUAL"),
    SUBTOTAL("#SUBTOTAL"),
    TOTAL_PERCEPCIONES("#TOTALPERCEPCIONES"),
    DESCUENTO("#DESCUENTO"),
    RETIMBRADO("#RETIMBRADO"),
    TOTAL_DEDUCCIONES("#TOTALDEDUCCIONES"),
    TOTAL_NETO("#TOTALNETO"),
    LUGAR_EXPEDICION("#LUGAREXPEDICION"),
    RFC_EMISOR("#RFCEMISOR"),
    NOMBRE_EMISOR("#NOMBREEMISOR"),
    RFC_RECEPTOR("#RFCREPECTOR"),
    NOMBRE_RECEPTOR("#NOMBRERECEPTOR"),
    DOMICILIO_RECEPTOR("#DOMICILIORECEPTOR"),
    RFC_SUBCONTRATACION("#RFCSUBCONTRATACION"),
    TIPO_PROCESO("#TIPOPROCESO"),
    FECHA_PAGO("#FECHAPAGO"),
    FORMA_PAGO("#FORMAPAGO"),
    PAGO_EXHIBICION("En una sola exhibición"),
    FECHA_INICIO("#FECHAINICIO"),
    FECHA_FIN("#FECHAFIN"),
    DIAS_PAGADOS("#DIASPAGADOS"),
    REGISTRO_PATRONAL("#REGISTROPATRONAL"),
    CURP_RECEPTOR("#CURPREPCEPTOR"),
    NUMERO_SEGURO_SOCIAL("#NSS"),
    FECHA_INICIO_LABORAL("#FECHAINLABORAL"),
    ANIOS_ANTIGUEDAD("#ANIOS"),
    ANTIGUEDAD("#ANTIGUEDAD"),
    TIPO_CONTRATO("#TIPOCONTRATO"),
    ES_SINDICALIZADO("#SINDICALIZADO"),
    NUMERO_EMPLEADO("#NUMEROEMPLEADO"),
    DEPARTAMENTO("#DEPARTAMENTO"),
    PUESTO("#PUESTO"),
    RIESGO_PUESTO("#RIESGOPUESTO"),
    PERIODICIDAD_PAGO("#PERIODICIDADPAGO"),
    SALARIO_DIARIO("#SALARIODIARIO"),
    SALARIO_INTEGRADO("#SALARIOINTEGRADO"),
    SUELDOS_SALARIOS("#SUELDOSSALARIOS"),
    TOTAL_GRAVADO_PERCEPCIONES("#TOTALGRAVADOP"),
    TOTAL_EXENTO_PERCEPCIONES("#TOTALEXENTOP"),
    IMPUESTO_RETENIDO("#IMPUESTORETENIDO"),
    ENCABEZADO_OTRAS_DEDUCCIONES("#ENCABEZADOOTRASDEDUCCIONES"),
    DETALLE_PERCEPCIONES("#DETALLEPERCEP"),
    DETALLE_DEDUCCIONES("#DETALLEDEDUC"),
    DETALLE_INCAPACIDADES("#DETALLEINCAPACIDADES"),
    DETALLE_OTROS_PAGOS("#DETALLEOTROSPAGOS"),
    ENZABEZADO_ISR("#ENCABEZADOISR"),
    SUBSIDIO_CAUSADO("#SUBSIDIOCAUSADO"),
    UNIDAD("Servicio"),
    CANTIDAD("1.00"),
    VERSION("1.2"),
    TOTAL_OTROS_PAGOS("#TOTALOTROSPAGOS"),
    TIPO_NOMINA("#TIPONOMINA"),
    NODO_DEDUCCIONES("#NODODEDUCCIONES"),
    NODO_PERCEPCIONES("#NODOPERCEPCIONES"),
    DEDUCCIONES("<nomina12:Deducciones #ENCABEZADOISR #ENCABEZADOOTRASDEDUCCIONES>#DETALLEDEDUC</nomina12:Deducciones>"),
    PERCEPCIONES("<nomina12:Percepciones TotalSueldos='#SUELDOSSALARIOS' TotalGravado='#TOTALGRAVADOP' TotalExento='#TOTALEXENTOP' #INDEMNIZACION>#DETALLEPERCEP</nomina12:Percepciones>"),
    DESCRIPCION("#DESCRIPCION"),
    CLAVE_REGIMEN_FISCAL_EMISOR("#REGIMENFISCALEMISOR");
//    
    private String concepto;

    private EtiquetasSat(String concepto) {
        this.concepto = concepto;
    }

    public String getConcepto() {
        return concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
}
